### ISSUE TITLE
Unnecessary image assets (flags, payment methods, etc.)

### ISSUE THREAD

**Issue by samarti** [lightyrs/tabler-rubygem#10]
When compiling assets all of the images are present, including hundreds of flags and payment icons which are generally not needed or not all of them at least. Would it be possible to make this assets optional? Or is there already a way?

**Comment by lightyrs** [comment]
This is not currently implemented but it's certainly possible. I encourage you or anyone else to submit a pull request adding this functionality. I will happily merge it.

**Comment by lightyrs** [comment]
This is solved by #12 and will be released to rubygems in the next few days @samarti.

**Comment by lightyrs** [comment]
@samarti The release has been published to [rubygems](https://rubygems.org/gems/tabler-rubygem/versions/0.1.4) and [github](https://github.com/lightyrs/tabler-rubygem/releases/tag/0.1.4).

**Comment by samarti** [comment]
Thanks!!
