### ISSUE TITLE
Update cycle

### ISSUE THREAD

**Issue by drale2k** [lightyrs/tabler-rubygem#2]
Hey, i am curious how often are you planning to pull commits from tabler into tabler-rubygem?

**Comment by lightyrs** [comment]
@drale2k I plan on doing it about once a month, however, the majority of the functionality of this gem is the update script, meaning, you can fork this gem and then run `rake update` to pull down the latest tabler master code.

**Comment by lightyrs** [comment]
@drale2k I see that https://github.com/tabler/tabler/tree/master/src/assets/scss is now depending on bootstrap from the `node_modules` directory, which means I'll have to rewrite the update rake task to pull bootstrap from another location. I probably won't have time this week so feel free to submit a PR.

**Comment by lightyrs** [comment]
@drale2k I've just updated the gem (and included the latest tabler master assets).  The installation method has changed so please check the README.
