### ISSUE TITLE
Precompile plugin.css

### ISSUE THREAD

**Issue by tryice3** [lightyrs/tabler-rubygem#7]
Hello and thanks for the gem.
Today I deployed my application on Heroku and all the css files that are under the plugins folder are not found. I imported them with @import "tabler.plugins". They are working fine if I set config.assets.compile = true, although it is not advised on production.

**Comment by lightyrs** [comment]
@fibice3 Thanks for reporting this. I suppose the solution here is to provide a precompiled version of all the plugins while still maintaining the ability to import specific plugins if needed. Does that sound right?

**Comment by drale2k** [comment]
+1 for this. I am importing the plugins via 

```
@import "tabler";
@import "tabler.plugins";
```

And getting the following error for all plugins. This is just one of them
`/assets/tabler/plugins/maps-google/plugin.css 404 (Not Found)`

**Comment by lightyrs** [comment]
This is being addressed by #8 (in progress).

**Comment by lightyrs** [comment]
This has been fixed in the latest release https://github.com/lightyrs/tabler-rubygem/releases/tag/0.1.3
