### ISSUE TITLE
Font Awesome Icons not working

### ISSUE THREAD

**Issue by drale2k** [lightyrs/tabler-rubygem#9]
Font Awesome icons can not be used for some reason. Feather and Flags work fine. When i try something like `<i class="fa fa-toggle-left"></i>` nothing is shown.

**Comment by lightyrs** [comment]
I did not implement font awesome for this gem. I encourage you or someone else to make a pull request. I will gladly merge it.

**Comment by alexmorral** [comment]
Wouldn't it be better if Font Awesome icons need to be installed separately? I mean, yes they could be on the gem as a dependency or even the css and svgs but maybe it's better if you install the icons that you want on your project manually: FontAwesome, Themify, etc.

**Comment by krtschmr** [comment]
@alexmorral i agree. dependencies for frontend are always a bad thing. escpecially since it's simply just a stylesheet tag into the CDN of fontawesome

**Comment by lightyrs** [comment]
Closing this with the understanding that fontawesome can be included as needed (but will not be a dependency of this project).
